### ISSUE TITLE
Exclude Tests from CodeCoverage

### ISSUE THREAD

**Issue by PeterHuewe** [tpm2-software/tpm2-tss#1377]
CodeCoverage should not include the testcases itself, but only the source to be tested.
This gives a more realistic view on the covered code.

**Comment by AndreasFuchsSIT** [comment]
Hmmm... we set the
https://github.com/tpm2-software/tpm2-tss/blob/e341d5dbc011a07c50d1d1015d23d2922ee3073b/Makefile.am#L29
but it happens after the
https://github.com/tpm2-software/tpm2-tss/blob/e341d5dbc011a07c50d1d1015d23d2922ee3073b/Makefile.am#L27

Or is it rather codecov.io ? and we need a `.codecov.yml` file to declare tests and library independently
- https://docs.codecov.io/docs/commit-status#section-excluding-tests-example-

There we should also set a threshold of `1%` i guess
- https://docs.codecov.io/docs/commit-status#section-threshold

I've tried to come up with a `.codecov.yml`
```
coverage:
  status:
    project:
      default: false
      tests:
        target: 90%
        paths: "test/"
      tpm2-tss:
        threshold: 1%
        paths: "!test/"  # remove all files in "tests/"
comment:
  behavior: new
```
What I don't know is how this will effect the badge or if we need a new badge-URL ?
Also, I have now declared the coverage-status rules for the project (on master I presume), but will this also affect PRs or not ?

I'll open a PR so we can have a look...

@tstruk @PeterHuewe What do you think, any updates / ideas ?
